<?php

namespace BehindSolution\LaravelQueryGate\TypeScript;

use Illuminate\Support\Str;

class TypesGenerator
{
    protected const BUILTIN_ACTIONS = ['create', 'update', 'delete', 'detail'];

    /**
     * Generate TypeScript content for a model definition.
     *
     * @param  string  $modelClass
     * @param  array<string, mixed>  $definition
     * @param  string|null  $version
     * @return string
     */
    public function generate(string $modelClass, array $definition, ?string $version = null): string
    {
        $alias = $definition['alias'] ?? $this->classToAlias($modelClass);
        $entity = $this->entityName($alias);

        return $this->buildContent($entity, $alias, $definition, $version);
    }

    /**
     * Convert a model class name to an alias.
     */
    protected function classToAlias(string $class): string
    {
        $basename = class_basename($class);

        return Str::snake(Str::plural($basename));
    }

    /**
     * Derive the singular PascalCase entity name from an alias.
     */
    protected function entityName(string $alias): string
    {
        return Str::studly(Str::singular($alias));
    }

    /**
     * Build the full TypeScript file content.
     *
     * @param  string  $entity
     * @param  string  $alias
     * @param  array<string, mixed>  $definition
     * @param  string|null  $version
     * @return string
     */
    protected function buildContent(string $entity, string $alias, array $definition, ?string $version): string
    {
        $lines = [];
        $lines[] = "// {$alias}.ts";
        $lines[] = '// Auto-generated by Laravel QueryGate - DO NOT EDIT';

        if ($version !== null) {
            $lines[] = "// Version: {$version}";
        }

        $lines[] = '';
        $lines[] = "import type { ResourceContract } from 'laravel-query-gate-sdk'";
        $lines[] = '';

        $select = $definition['select'] ?? [];
        $filters = $definition['filters'] ?? [];
        $actions = $definition['actions'] ?? [];
        $hasEntity = !empty($select);

        // Entity interface
        if ($hasEntity) {
            $lines[] = $this->generateEntityInterface($entity, $select, $filters);
        }

        // Create payload
        $createPayloadName = null;

        if (isset($actions['create'])) {
            $validation = $actions['create']['validation'] ?? null;

            if (is_array($validation) && $validation !== []) {
                $createPayloadName = "Create{$entity}Payload";
                $lines[] = $this->generatePayloadInterface($createPayloadName, $validation);
            }
        }

        // Update payload
        $updatePayloadName = null;

        if (isset($actions['update'])) {
            $validation = $actions['update']['validation'] ?? null;

            if (is_array($validation) && $validation !== []) {
                $updatePayloadName = "Update{$entity}Payload";
                $lines[] = $this->generatePayloadInterface($updatePayloadName, $validation);
            }
        }

        // Contract
        $lines[] = $this->generateContract($entity, $hasEntity, $createPayloadName, $updatePayloadName, $actions);

        return implode("\n", $lines);
    }

    /**
     * Generate the entity interface from select fields with types inferred from filters.
     *
     * @param  string  $entity
     * @param  array<int, string>  $select
     * @param  array<string, mixed>  $filters
     * @return string
     */
    protected function generateEntityInterface(string $entity, array $select, array $filters): string
    {
        $lines = [];
        $lines[] = "/** {$entity} entity */";
        $lines[] = "export interface {$entity} {";

        foreach ($select as $field) {
            $formattedField = $this->formatKey($field);
            $tsType = 'unknown';

            if (isset($filters[$field])) {
                $rules = $this->normalizeRules($filters[$field]);
                $tsType = $this->phpRulesToTypeScriptType($rules);

                if ($this->isNullable($rules)) {
                    $tsType .= ' | null';
                }
            }

            $lines[] = "  {$formattedField}: {$tsType}";
        }

        $lines[] = '}';
        $lines[] = '';

        return implode("\n", $lines);
    }

    /**
     * Generate a payload interface from action validation rules.
     *
     * @param  string  $name
     * @param  array<string, mixed>  $validationRules
     * @return string
     */
    protected function generatePayloadInterface(string $name, array $validationRules): string
    {
        $lines = [];
        $lines[] = "/** {$name} */";
        $lines[] = "export interface {$name} {";

        foreach ($validationRules as $field => $rules) {
            if (str_contains($field, '.*')) {
                continue;
            }

            $rules = $this->normalizeRules($rules);
            $formattedField = $this->formatKey($field);
            $required = $this->isRequiredField($rules);
            $tsType = $this->resolveFieldType($field, $rules, $validationRules);

            if ($this->isNullable($rules)) {
                $tsType .= ' | null';
            }

            $optional = $required ? '' : '?';
            $lines[] = "  {$formattedField}{$optional}: {$tsType}";
        }

        $lines[] = '}';
        $lines[] = '';

        return implode("\n", $lines);
    }

    /**
     * Generate the ResourceContract interface.
     *
     * @param  string  $entity
     * @param  bool  $hasEntity
     * @param  string|null  $createPayloadName
     * @param  string|null  $updatePayloadName
     * @param  array<string, mixed>  $actions
     * @return string
     */
    protected function generateContract(
        string $entity,
        bool $hasEntity,
        ?string $createPayloadName,
        ?string $updatePayloadName,
        array $actions,
    ): string {
        $contractName = "{$entity}Contract";
        $lines = [];
        $lines[] = "/** Contract for the {$entity} resource */";
        $lines[] = "export interface {$contractName} extends ResourceContract {";

        // get
        $getType = $hasEntity ? "{$entity}[]" : 'unknown[]';
        $lines[] = "  get: {$getType}";

        // create
        if (isset($actions['create'])) {
            $createType = $createPayloadName ?? 'Record<string, unknown>';
            $lines[] = "  create: {$createType}";
        }

        // update
        if (isset($actions['update'])) {
            $updateType = $updatePayloadName ?? 'Record<string, unknown>';
            $lines[] = "  update: {$updateType}";
        }

        // Custom actions
        $customActions = array_filter(
            $actions,
            fn ($key) => !in_array($key, self::BUILTIN_ACTIONS, true),
            ARRAY_FILTER_USE_KEY,
        );

        if ($customActions !== []) {
            $lines[] = '  actions: {';

            foreach ($customActions as $actionName => $config) {
                $actionLines = $this->generateActionEntry($actionName, $config);

                foreach ($actionLines as $line) {
                    $lines[] = $line;
                }
            }

            $lines[] = '  }';
        }

        $lines[] = '}';
        $lines[] = '';

        return implode("\n", $lines);
    }

    /**
     * Generate a single action entry within the actions block.
     *
     * @param  string  $actionName
     * @param  array<string, mixed>  $config
     * @return array<int, string>
     */
    protected function generateActionEntry(string $actionName, array $config): array
    {
        $formattedName = $this->formatKey($actionName);
        $method = strtolower($config['method'] ?? 'post');
        $validation = $config['validation'] ?? null;

        $lines = [];
        $lines[] = "    {$formattedName}: {";
        $lines[] = "      method: '{$method}'";

        if (is_array($validation) && $validation !== []) {
            $payloadType = $this->generateInlinePayloadType($validation);
            $lines[] = "      payload: {$payloadType}";
        } else {
            $lines[] = '      payload?: never';
        }

        $lines[] = '      response: unknown';
        $lines[] = '    }';

        return $lines;
    }

    /**
     * Generate an inline object type from validation rules.
     *
     * @param  array<string, mixed>  $validationRules
     * @return string
     */
    protected function generateInlinePayloadType(array $validationRules): string
    {
        $parts = [];

        foreach ($validationRules as $field => $rules) {
            if (str_contains($field, '.*')) {
                continue;
            }

            $rules = $this->normalizeRules($rules);
            $formattedField = $this->formatKey($field);
            $required = $this->isRequiredField($rules);
            $tsType = $this->resolveFieldType($field, $rules, $validationRules);

            if ($this->isNullable($rules)) {
                $tsType .= ' | null';
            }

            $optional = $required ? '' : '?';
            $parts[] = "{$formattedField}{$optional}: {$tsType}";
        }

        return '{ ' . implode(', ', $parts) . ' }';
    }

    /**
     * Resolve the TypeScript type for a field, handling array item types via field.* notation.
     *
     * @param  string  $field
     * @param  array<int, mixed>  $rules
     * @param  array<string, mixed>  $allRules
     * @return string
     */
    protected function resolveFieldType(string $field, array $rules, array $allRules): string
    {
        $baseType = $this->phpRulesToTypeScriptType($rules);

        if ($baseType === 'unknown[]' && isset($allRules["{$field}.*"])) {
            $itemRules = $this->normalizeRules($allRules["{$field}.*"]);
            $itemType = $this->phpRulesToTypeScriptType($itemRules);

            return "{$itemType}[]";
        }

        return $baseType;
    }

    /**
     * Normalize validation rules to an array of strings.
     *
     * @param  mixed  $rules
     * @return array<int, string>
     */
    protected function normalizeRules($rules): array
    {
        if (is_string($rules)) {
            return explode('|', $rules);
        }

        if (is_array($rules)) {
            return $rules;
        }

        return [];
    }

    /**
     * Check if validation rules include 'required'.
     *
     * @param  array<int, mixed>  $rules
     * @return bool
     */
    protected function isRequiredField(array $rules): bool
    {
        foreach ($rules as $rule) {
            if (is_string($rule) && strtolower($rule) === 'required') {
                return true;
            }
        }

        return false;
    }

    /**
     * Check if validation rules include 'nullable'.
     *
     * @param  array<int, mixed>  $rules
     * @return bool
     */
    protected function isNullable(array $rules): bool
    {
        foreach ($rules as $rule) {
            if (is_string($rule) && strtolower($rule) === 'nullable') {
                return true;
            }
        }

        return false;
    }

    /**
     * Convert PHP validation rules to a TypeScript type.
     *
     * @param  array<int, mixed>  $rules
     * @return string
     */
    protected function phpRulesToTypeScriptType(array $rules): string
    {
        foreach ($rules as $rule) {
            if (!is_string($rule)) {
                continue;
            }

            $rule = strtolower($rule);

            if (in_array($rule, ['integer', 'int', 'numeric'], true)) {
                return 'number';
            }

            if (in_array($rule, ['boolean', 'bool'], true)) {
                return 'boolean';
            }

            if ($rule === 'array') {
                return 'unknown[]';
            }

            if (in_array($rule, ['date', 'date_format'], true)) {
                return 'string';
            }

            if (in_array($rule, ['string', 'email', 'url'], true)) {
                return 'string';
            }
        }

        return 'unknown';
    }

    /**
     * Format a property key for TypeScript.
     * Keys with special characters (hyphens, dots, etc.) must be quoted.
     */
    protected function formatKey(string $key): string
    {
        if (preg_match('/[^a-zA-Z0-9_$]/', $key) || preg_match('/^[0-9]/', $key)) {
            return "'{$key}'";
        }

        return $key;
    }

    /**
     * Convert a string to camelCase.
     */
    protected function toCamelCase(string $value): string
    {
        return Str::camel($value);
    }
}
