<?php

namespace BehindSolution\LaravelQueryGate\Tests\Feature;

use BehindSolution\LaravelQueryGate\Support\QueryGate;
use BehindSolution\LaravelQueryGate\Tests\Fixtures\Post;
use BehindSolution\LaravelQueryGate\Tests\TestCase;

class TypesCommandTest extends TestCase
{
    protected string $outputDir;

    protected function setUp(): void
    {
        parent::setUp();
        $this->outputDir = storage_path('app/query-gate-types-test');
    }

    protected function tearDown(): void
    {
        $this->cleanupOutputDir();
        parent::tearDown();
    }

    protected function cleanupOutputDir(): void
    {
        if (is_dir($this->outputDir)) {
            $files = glob($this->outputDir . '/*');
            if ($files) {
                foreach ($files as $file) {
                    @unlink($file);
                }
            }
            @rmdir($this->outputDir);
        }
    }

    public function testGeneratesTypeScriptFiles(): void
    {
        $this->cleanupOutputDir();

        config()->set('query-gate.models.' . Post::class, QueryGate::make()
            ->alias('posts')
            ->filters([
                'title' => ['required', 'string', 'max:255'],
                'views' => ['integer'],
            ])
            ->allowedFilters([
                'title' => ['eq', 'like'],
                'views' => ['gte', 'lte'],
            ])
            ->select(['id', 'title', 'content', 'created_at'])
            ->actions(fn ($actions) => $actions
                ->create()
                ->update()
                ->delete()
            )
            ->sorts(['title', 'created_at'])
        );

        $this->artisan('qg:types', ['--output' => $this->outputDir])
            ->assertExitCode(0);

        $this->assertDirectoryExists($this->outputDir);
        $this->assertFileExists($this->outputDir . '/posts.ts');
        $this->assertFileExists($this->outputDir . '/index.ts');

        $postsContent = file_get_contents($this->outputDir . '/posts.ts');
        $this->assertIsString($postsContent);

        // Check file header
        $this->assertStringContainsString('// posts.ts', $postsContent);
        $this->assertStringContainsString('Auto-generated by Laravel QueryGate', $postsContent);

        // Check filters interface
        $this->assertStringContainsString('export interface PostsFilters', $postsContent);
        $this->assertStringContainsString('title?: string', $postsContent);
        $this->assertStringContainsString('views?: number', $postsContent);

        // Check operators interface
        $this->assertStringContainsString('export interface PostsOperators', $postsContent);
        $this->assertStringContainsString("title: ('eq' | 'like')[]", $postsContent);
        $this->assertStringContainsString("views: ('gte' | 'lte')[]", $postsContent);

        // Check select type
        $this->assertStringContainsString('export type PostsSelectField', $postsContent);
        $this->assertStringContainsString("'id'", $postsContent);
        $this->assertStringContainsString("'title'", $postsContent);

        // Check sort type
        $this->assertStringContainsString('export type PostsSortField', $postsContent);

        // Check actions interface
        $this->assertStringContainsString('export interface PostsActions', $postsContent);
        $this->assertStringContainsString("create: { method: 'POST' }", $postsContent);
        $this->assertStringContainsString("update: { method: 'PATCH' }", $postsContent);
        $this->assertStringContainsString("delete: { method: 'DELETE' }", $postsContent);

        // Check config object
        $this->assertStringContainsString('export const postsConfig', $postsContent);
        $this->assertStringContainsString("alias: 'posts'", $postsContent);

        // Check index.ts
        $indexContent = file_get_contents($this->outputDir . '/index.ts');
        $this->assertIsString($indexContent);
        $this->assertStringContainsString("export * from './posts'", $indexContent);
    }

    public function testWarnsWhenNoModelsConfigured(): void
    {
        $this->cleanupOutputDir();

        config()->set('query-gate.models', []);

        $this->artisan('qg:types', ['--output' => $this->outputDir])
            ->expectsOutput('No Query Gate models configured.')
            ->assertExitCode(0);
    }

    public function testGeneratesTypesWithVersions(): void
    {
        $this->cleanupOutputDir();

        config()->set('query-gate.models.' . Post::class, QueryGate::make()
            ->alias('posts')
            ->filters(['title' => 'string'])
            ->version('2024-01-01', function ($v) {
                $v->filters(['title' => 'string']);
            })
            ->version('2024-06-01', function ($v) {
                $v->filters(['title' => 'string', 'status' => 'string']);
            })
        );

        $this->artisan('qg:types', ['--output' => $this->outputDir])
            ->assertExitCode(0);

        $postsContent = file_get_contents($this->outputDir . '/posts.ts');
        $this->assertIsString($postsContent);

        // Should use latest version by default
        $this->assertStringContainsString("version: '2024-06-01'", $postsContent);
    }

    public function testGeneratesTypesWithSpecificVersion(): void
    {
        $this->cleanupOutputDir();

        config()->set('query-gate.models.' . Post::class, QueryGate::make()
            ->alias('posts')
            ->filters(['title' => 'string'])
            ->version('2024-01-01', function ($v) {
                $v->filters(['title' => 'string']);
            })
            ->version('2024-06-01', function ($v) {
                $v->filters(['title' => 'string', 'status' => 'string']);
            })
        );

        $this->artisan('qg:types', ['--output' => $this->outputDir, '--api-version' => '2024-01-01'])
            ->assertExitCode(0);

        $postsContent = file_get_contents($this->outputDir . '/posts.ts');
        $this->assertIsString($postsContent);

        $this->assertStringContainsString("version: '2024-01-01'", $postsContent);
    }

    public function testUsesDefaultOutputPath(): void
    {
        $defaultPath = storage_path('app/query-gate-types');

        // Clean up default path
        if (is_dir($defaultPath)) {
            $files = glob($defaultPath . '/*');
            if ($files) {
                foreach ($files as $file) {
                    @unlink($file);
                }
            }
            @rmdir($defaultPath);
        }

        config()->set('query-gate.models.' . Post::class, QueryGate::make()
            ->alias('posts')
            ->filters(['title' => 'string'])
        );

        $this->artisan('qg:types')
            ->assertExitCode(0);

        $this->assertDirectoryExists($defaultPath);
        $this->assertFileExists($defaultPath . '/posts.ts');
        $this->assertFileExists($defaultPath . '/index.ts');

        // Clean up
        $files = glob($defaultPath . '/*');
        if ($files) {
            foreach ($files as $file) {
                @unlink($file);
            }
        }
        @rmdir($defaultPath);
    }

    public function testGeneratesTypeWithClassNameWhenNoAlias(): void
    {
        $this->cleanupOutputDir();

        config()->set('query-gate.models.' . Post::class, QueryGate::make()
            ->filters(['title' => 'string'])
        );

        $this->artisan('qg:types', ['--output' => $this->outputDir])
            ->assertExitCode(0);

        // Should use snake_case plural of class name
        $this->assertFileExists($this->outputDir . '/posts.ts');
    }
}
