<?php

namespace BehindSolution\LaravelQueryGate\Tests\Feature;

use BehindSolution\LaravelQueryGate\Support\QueryGate;
use BehindSolution\LaravelQueryGate\Tests\Fixtures\Post;
use BehindSolution\LaravelQueryGate\Tests\Stubs\Actions\BulkPublishPostsAction;
use BehindSolution\LaravelQueryGate\Tests\TestCase;

class TypesCommandTest extends TestCase
{
    protected string $outputDir;

    protected function setUp(): void
    {
        parent::setUp();
        $this->outputDir = storage_path('app/query-gate-types-test');
    }

    protected function tearDown(): void
    {
        $this->cleanupOutputDir();
        parent::tearDown();
    }

    protected function cleanupOutputDir(): void
    {
        if (is_dir($this->outputDir)) {
            $files = glob($this->outputDir . '/*');
            if ($files) {
                foreach ($files as $file) {
                    @unlink($file);
                }
            }
            @rmdir($this->outputDir);
        }
    }

    public function testGeneratesResourceContractFormat(): void
    {
        $this->cleanupOutputDir();

        config()->set('query-gate.models.' . Post::class, QueryGate::make()
            ->alias('posts')
            ->filters([
                'title' => ['required', 'string', 'max:255'],
                'views' => ['integer'],
            ])
            ->allowedFilters([
                'title' => ['eq', 'like'],
                'views' => ['gte', 'lte'],
            ])
            ->select(['id', 'title', 'content', 'views', 'created_at'])
            ->actions(fn ($actions) => $actions
                ->create(fn ($action) => $action
                    ->validations([
                        'title' => ['required', 'string'],
                        'content' => ['required', 'string'],
                    ])
                )
                ->update(fn ($action) => $action
                    ->validations([
                        'title' => ['string'],
                        'content' => ['string'],
                    ])
                )
                ->delete()
            )
            ->sorts(['title', 'created_at'])
        );

        $this->artisan('qg:types', ['--output' => $this->outputDir])
            ->assertExitCode(0);

        $this->assertDirectoryExists($this->outputDir);
        $this->assertFileExists($this->outputDir . '/posts.ts');
        $this->assertFileExists($this->outputDir . '/index.ts');

        $content = file_get_contents($this->outputDir . '/posts.ts');
        $this->assertIsString($content);

        // Header
        $this->assertStringContainsString('// posts.ts', $content);
        $this->assertStringContainsString('Auto-generated by Laravel QueryGate', $content);

        // Import
        $this->assertStringContainsString("import type { ResourceContract } from 'laravel-query-gate-sdk'", $content);

        // Entity interface (singular PascalCase)
        $this->assertStringContainsString('export interface Post {', $content);
        $this->assertStringContainsString('id: unknown', $content);
        $this->assertStringContainsString('title: string', $content);
        $this->assertStringContainsString('content: unknown', $content);
        $this->assertStringContainsString('views: number', $content);
        $this->assertStringContainsString('created_at: unknown', $content);

        // Create payload
        $this->assertStringContainsString('export interface CreatePostPayload {', $content);
        $this->assertStringContainsString('title: string', $content);
        $this->assertStringContainsString('content: string', $content);

        // Update payload (optional fields)
        $this->assertStringContainsString('export interface UpdatePostPayload {', $content);
        $this->assertStringContainsString('title?: string', $content);
        $this->assertStringContainsString('content?: string', $content);

        // Contract
        $this->assertStringContainsString('export interface PostContract extends ResourceContract {', $content);
        $this->assertStringContainsString('get: Post[]', $content);
        $this->assertStringContainsString('create: CreatePostPayload', $content);
        $this->assertStringContainsString('update: UpdatePostPayload', $content);

        // No old format remnants
        $this->assertStringNotContainsString('PostsFilters', $content);
        $this->assertStringNotContainsString('PostsOperators', $content);
        $this->assertStringNotContainsString('PostsSelectField', $content);
        $this->assertStringNotContainsString('PostsSortField', $content);
        $this->assertStringNotContainsString('postsConfig', $content);
        $this->assertStringNotContainsString('as const', $content);

        // Index file
        $indexContent = file_get_contents($this->outputDir . '/index.ts');
        $this->assertIsString($indexContent);
        $this->assertStringContainsString("export * from './posts'", $indexContent);
    }

    public function testGeneratesCustomActionsWithPayload(): void
    {
        $this->cleanupOutputDir();

        config()->set('query-gate.models.' . Post::class, QueryGate::make()
            ->alias('posts')
            ->select(['id', 'title'])
            ->filters(['title' => ['string']])
            ->actions(fn ($actions) => $actions
                ->create()
                ->use(BulkPublishPostsAction::class)
            )
        );

        $this->artisan('qg:types', ['--output' => $this->outputDir])
            ->assertExitCode(0);

        $content = file_get_contents($this->outputDir . '/posts.ts');
        $this->assertIsString($content);

        // Custom action with hyphenated name, lowercase method, and payload
        $this->assertStringContainsString("'bulk-publish': {", $content);
        $this->assertStringContainsString("method: 'post'", $content);
        $this->assertStringContainsString('payload: {', $content);
        $this->assertStringContainsString('response: unknown', $content);

        // Array with item type inference (ids: ['required', 'array'], ids.*: ['integer'] → number[])
        $this->assertStringContainsString('ids: number[]', $content);

        // Built-in create should NOT appear in actions block
        $this->assertStringNotContainsString("create: {", $content);
    }

    public function testGeneratesActionWithoutPayload(): void
    {
        $this->cleanupOutputDir();

        config()->set('query-gate.models.' . Post::class, QueryGate::make()
            ->alias('posts')
            ->select(['id', 'title'])
            ->actions(fn ($actions) => $actions
                ->create()
                ->detail()
            )
        );

        $this->artisan('qg:types', ['--output' => $this->outputDir])
            ->assertExitCode(0);

        $content = file_get_contents($this->outputDir . '/posts.ts');
        $this->assertIsString($content);

        // Create without validation → Record<string, unknown>
        $this->assertStringContainsString('create: Record<string, unknown>', $content);

        // No actions block (all are built-in)
        $this->assertStringNotContainsString('actions: {', $content);
    }

    public function testGeneratesContractWithoutEntity(): void
    {
        $this->cleanupOutputDir();

        config()->set('query-gate.models.' . Post::class, QueryGate::make()
            ->alias('posts')
            ->filters(['title' => 'string'])
        );

        $this->artisan('qg:types', ['--output' => $this->outputDir])
            ->assertExitCode(0);

        $content = file_get_contents($this->outputDir . '/posts.ts');
        $this->assertIsString($content);

        // No entity interface (no select)
        $this->assertStringNotContainsString('export interface Post {', $content);

        // Contract with unknown[] for get
        $this->assertStringContainsString('get: unknown[]', $content);

        // No create/update (no actions)
        $this->assertStringNotContainsString('create:', $content);
        $this->assertStringNotContainsString('update:', $content);
    }

    public function testGeneratesContractWithoutCreateUpdate(): void
    {
        $this->cleanupOutputDir();

        config()->set('query-gate.models.' . Post::class, QueryGate::make()
            ->alias('posts')
            ->select(['id', 'title'])
            ->filters(['title' => ['string']])
        );

        $this->artisan('qg:types', ['--output' => $this->outputDir])
            ->assertExitCode(0);

        $content = file_get_contents($this->outputDir . '/posts.ts');
        $this->assertIsString($content);

        // Entity is generated
        $this->assertStringContainsString('export interface Post {', $content);
        $this->assertStringContainsString('get: Post[]', $content);

        // No create/update in contract
        $this->assertStringNotContainsString('create:', $content);
        $this->assertStringNotContainsString('update:', $content);
        $this->assertStringNotContainsString('CreatePostPayload', $content);
        $this->assertStringNotContainsString('UpdatePostPayload', $content);
    }

    public function testQuotesKeysWithSpecialCharacters(): void
    {
        $this->cleanupOutputDir();

        config()->set('query-gate.models.' . Post::class, QueryGate::make()
            ->alias('posts')
            ->filters([
                'title' => ['string'],
                'author.name' => ['string'],
            ])
            ->select(['id', 'title', 'author.name'])
            ->actions(fn ($actions) => $actions
                ->create()
                ->use(BulkPublishPostsAction::class)
            )
        );

        $this->artisan('qg:types', ['--output' => $this->outputDir])
            ->assertExitCode(0);

        $content = file_get_contents($this->outputDir . '/posts.ts');
        $this->assertIsString($content);

        // Dotted keys must be quoted in entity
        $this->assertStringContainsString("'author.name': string", $content);

        // Non-special keys should NOT be quoted
        $this->assertStringContainsString('title: string', $content);

        // Hyphenated keys must be quoted in actions
        $this->assertStringContainsString("'bulk-publish': {", $content);
    }

    public function testHandlesNullableFields(): void
    {
        $this->cleanupOutputDir();

        config()->set('query-gate.models.' . Post::class, QueryGate::make()
            ->alias('posts')
            ->filters([
                'title' => ['string'],
                'status' => ['nullable', 'string'],
            ])
            ->select(['id', 'title', 'status'])
            ->actions(fn ($actions) => $actions
                ->create(fn ($action) => $action
                    ->validations([
                        'title' => ['required', 'string'],
                        'status' => ['nullable', 'string'],
                    ])
                )
            )
        );

        $this->artisan('qg:types', ['--output' => $this->outputDir])
            ->assertExitCode(0);

        $content = file_get_contents($this->outputDir . '/posts.ts');
        $this->assertIsString($content);

        // Entity: nullable field
        $this->assertStringContainsString('status: string | null', $content);

        // Payload: nullable optional field
        $this->assertStringContainsString('status?: string | null', $content);
    }

    public function testWarnsWhenNoModelsConfigured(): void
    {
        $this->cleanupOutputDir();

        config()->set('query-gate.models', []);

        $this->artisan('qg:types', ['--output' => $this->outputDir])
            ->expectsOutput('No Query Gate models configured.')
            ->assertExitCode(0);
    }

    public function testGeneratesTypesWithVersions(): void
    {
        $this->cleanupOutputDir();

        config()->set('query-gate.models.' . Post::class, QueryGate::make()
            ->alias('posts')
            ->filters(['title' => 'string'])
            ->select(['id', 'title'])
            ->version('2024-01-01', function ($v) {
                $v->filters(['title' => 'string']);
            })
            ->version('2024-06-01', function ($v) {
                $v->filters(['title' => 'string', 'status' => 'string']);
            })
        );

        $this->artisan('qg:types', ['--output' => $this->outputDir])
            ->assertExitCode(0);

        $content = file_get_contents($this->outputDir . '/posts.ts');
        $this->assertIsString($content);

        $this->assertStringContainsString("Version: 2024-06-01", $content);
    }

    public function testGeneratesTypeWithClassNameWhenNoAlias(): void
    {
        $this->cleanupOutputDir();

        config()->set('query-gate.models.' . Post::class, QueryGate::make()
            ->filters(['title' => 'string'])
        );

        $this->artisan('qg:types', ['--output' => $this->outputDir])
            ->assertExitCode(0);

        $this->assertFileExists($this->outputDir . '/posts.ts');
    }

    public function testUsesDefaultOutputPath(): void
    {
        $defaultPath = storage_path('app/query-gate-types');

        if (is_dir($defaultPath)) {
            $files = glob($defaultPath . '/*');
            if ($files) {
                foreach ($files as $file) {
                    @unlink($file);
                }
            }
            @rmdir($defaultPath);
        }

        config()->set('query-gate.models.' . Post::class, QueryGate::make()
            ->alias('posts')
            ->filters(['title' => 'string'])
        );

        $this->artisan('qg:types')
            ->assertExitCode(0);

        $this->assertDirectoryExists($defaultPath);
        $this->assertFileExists($defaultPath . '/posts.ts');
        $this->assertFileExists($defaultPath . '/index.ts');

        $files = glob($defaultPath . '/*');
        if ($files) {
            foreach ($files as $file) {
                @unlink($file);
            }
        }
        @rmdir($defaultPath);
    }
}
